### ISSUE TITLE
Bullet points don’t appear on iOS

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/Website#12]
Safari/Firefox/PWA iOS 14.42

FF:
Mozilla/5.0 (iPhone; CPU OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/33.0 Mobile/15E148 Safari/605.1.15

Safari:
Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1

**Comment by HandyHat** [comment]
Cannot repro on good hardware. Can confirm it's an iOS issue. As apple bad, cannot troubleshoot

**Comment by ajhawkings** [comment]
we ❤️ Apple

**Comment by HandyHat** [comment]
Bullet Points still not appearing

**Comment by ajhawkings** [comment]
> Bullet Points still not appearing

What device? What version. Works for me

**Comment by ajhawkings** [comment]
Cannot reproduce

**Comment by HandyHat** [comment]
> What device? What version. Works for me

Tested on Charlie's phone this morning. idk what device etc.

**Comment by HandyHat** [comment]
Seems to be fixed in iOS 14.5.
