### ISSUE TITLE
Maybe make dates in lunch and calendar bold?

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/Website#13]
Hard to tell dates apart - emphasis or something would be nice - especially when the screen width is small and the text goes onto two lines

**Comment by Epacnoss** [comment]
OK. If you feel this is important, feel free to add the <b></b> tags to all of it yourself. Either that or do it in the stylesheets.

I see what you mean, but I don't feel that it is a problem.

**Comment by ajhawkings** [comment]
Well that’s a downvote if I’ve ever seen one

**Comment by ajhawkings** [comment]
@Epacnoss didn’t want it and it will become obsolescent as a result of project delta (no one else came up with a good name) so closing this!

**Comment by Epacnoss** [comment]
Project Delta @ajhawkings ?

**Comment by HandyHat** [comment]
> Project Delta
I'm assuming that's #18 

BTW I did try this and idk if it's the font we are using or what but I could see no difference
