### ISSUE TITLE
Team names should probs be capitalised

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/Website#20]

**Comment by Epacnoss** [comment]
DO IT YOURSELF.
JUST MAKE A COMMIT/PR.

**Comment by ajhawkings** [comment]
Should have added “I’m too lazy to do it that’s why I’m opening an issue”

**Comment by HandyHat** [comment]
Team names?

**Comment by ajhawkings** [comment]
Sport teams

**Comment by HandyHat** [comment]
Oh the letters? I did try this but A team conflicted with Away as on the calendar it just says A for away

**Comment by ajhawkings** [comment]
Ok fine
