### ISSUE TITLE
Going back from images in PWA

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/Website#26]
From what I can tell its pretty hard to go back within PWAs, so when clicking on one image, you have to right-click the title bar and click back to go back to the main page - not user-friendly. 
A solution would be using an html page and adding a back button.

**Comment by HandyHat** [comment]
> A solution would be using an html page and adding a back button.

CRINGE
we love PWAs

**Comment by HandyHat** [comment]
not fixed because SAFARI BAD WE HATE APPLE APPLE DOESNT ALLOW DIFFERENT BROWSER ENGINES STUPID APPLE

**Comment by ajhawkings** [comment]
ok so on pc we need minimal ui coz there is no back button
whereas on mobile, pwa ui is fine coz u can swipe back
im assuming theres no way to split it?

**Comment by HandyHat** [comment]
Depends on how Apple implemented stuff. I'm still trying to figure out exactly what they support and what they don't (and I'll probably end up submitting a PR to MDN docs) and then see if it works. Would be a lot of easier if stupid apple let me set up a test device...
WE HATE APPLE

**Comment by ajhawkings** [comment]
USE BROWSERSTACK

**Comment by ajhawkings** [comment]
Also you can get an iOS emulator with Xcode :P

**Comment by HandyHat** [comment]
you still have to buy apples stupid hardware for that

**Comment by HandyHat** [comment]
Also tried browserstack and it doesn't seem to support PWAs

**Comment by ajhawkings** [comment]
> you still have to buy apples stupid hardware for that

Yes but apples hardware is pogggggers

**Comment by ajhawkings** [comment]
You could use a Mac vps

**Comment by HandyHat** [comment]
No I'm not buying apple's stupid overpriced hardware to cater to their users. all stupid apple are doing is making the experience worse for their users 🤷🏾

**Comment by HandyHat** [comment]
@ajhawkings please test now

**Comment by ajhawkings** [comment]
Oh

**Comment by ajhawkings** [comment]
not fixed

**Comment by ajhawkings** [comment]
not fixed - you still can't get back from images easily on desktop

**Comment by ajhawkings** [comment]
it has a back button on edge pwa but not when i reinstall chrome pwa

**Comment by HandyHat** [comment]
This seems like a you problem - I have a backbutton on chrome pwa.
try going to https://l5info.live/site.webmanifest to force it to update, then go to `chrome://restart`
Then reinstall the app

**Comment by ajhawkings** [comment]
Nope doesn't work for me

**Comment by ajhawkings** [comment]
I've never seen a back button on anyone else's desktop pwa

**Comment by ajhawkings** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

**Comment by HandyHat** [comment]
Lol that's too out of date. We are using `display_override`, which is supported as of chromium 89 and above. The latest stable is 91 - please update.

**Comment by ajhawkings** [comment]
Lol idk how. Are our users on new versions? Will the pwa update without reinstallation?

**Comment by ajhawkings** [comment]
google bad

**Comment by ajhawkings** [comment]
Ok I'm reasonably sure it auto updates and that it was just ungoogled chromium deciding to not have a way to update. Sorry for re-opening

**Comment by HandyHat** [comment]
>Ok I'm reasonably sure it auto updates 

Chrome does indeed auto-update

> it was just ungoogled chromium deciding to not have a way to update.

Ahhh imagine using ungoogled chromium @ajhawkings 

> Are our users on new versions?

Not sure but I think it's safe to assume so. Google Analytics should tell us exactly what browser version people are on but I think it's hiding the data because we don't have enough users (to ensure we can't identify indviduals in the data). Seeing as this is only relevant to desktop chrome users i think we are fine.

> Will the pwa update without reinstallation?

Chrome has specific criteria that it uses to decide when to update the web manifest (see: https://web.dev/manifest-updates/). I think we should be fine as after I added `display_override` (f7bcb74381861db5a76bdded31aa3c0e4674c383) I added shortcuts (f07fc10b968780a5d6f796ed2fb5a69a471fb158)

**Comment by ajhawkings** [comment]
> Chrome does indeed auto-update 
That was refering to the PWA, which I confirmed updated on another device
> Ahhh imagine using ungoogled chromium @ajhawkings @benstockil 
imagine having google tracking you cough FLoC
> Not sure but I think it's safe to assume so. Google Analytics should tell us exactly what browser version people are on but I think it's hiding the data because we don't have enough users (to ensure we can't identify indviduals in the data). Seeing as this is only relevant to desktop chrome users i think we are fine.
Ah so google bad again - understood
> Chrome has specific criteria that it uses to decide when to update the web manifest - I think we should be fine as after I added display_override (f7bcb74) I added shortcuts (f07fc10)
yeh all good
