### ISSUE TITLE
WatchOS doesn't support WebP

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/Website#27]
ok we solved the back button without putting images into HTML, we solved the macOS support without putting them into HTML, but it finally has to happen - we overlooked Apple Watch support - they can't view standalone images afaik

**Comment by HandyHat** [comment]
do we even know if watchos supports webp?
apple has no good documentation (because they like making life as hard as possible for devs)

**Comment by Epacnoss** [comment]
But is anyone really viewing images on apple watches?
Screen is too small to be useful.
Its like catering for IE users.

**Comment by HandyHat** [comment]
Still an issue

**Comment by Epacnoss** [comment]
**IT WAS NEVER EVEN AN ISSUE**

**Comment by Epacnoss** [comment]
use big google.
Apple no support webp

_**APPLE BAD**_

**Comment by HandyHat** [comment]
Looks like if you actually convert the png to webp (like @ajhawkings likes to do), then it doesn't display on WatchOS (i.e. apple lied in their [documentation](https://developer.apple.com/documentation/uniformtypeidentifiers/uttype/3551599-webp).

Instead you can take a png and replace the extension to webp, pleasing big google and working around apple
