### ISSUE TITLE
exam timetable out of date

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/Website#28]

**Comment by HandyHat** [comment]
wow i was just about to open this

**Comment by Epacnoss** [comment]
![image](https://user-images.githubusercontent.com/49815482/119790290-b8066f00-becb-11eb-8598-b631d5bf1d6e.png)

**Comment by Epacnoss** [comment]
new tt

**Comment by ajhawkings** [comment]
cool
needs webp conversion

**Comment by HandyHat** [comment]
Closed in 032378c
