### ISSUE TITLE
Making PWA names coherent

### ISSUE THREAD

**Issue by ajhawkings** [YearInfo/Website#32]
Currently our long PWA name is "Lower Fifth Info" and the short one is "L5 info". 
I think it makes sense to go for L5 info on both - as it's confusing to have one name to search for on Windows and a different name on iOS. Also people really know us as l5info, not Lower Fifth info
cc @HandyHat

**Comment by HandyHat** [comment]
Nice sentiment but changing the PWA name breaks it
![Screenshot_20210615-162723.png](https://user-images.githubusercontent.com/58530748/122081034-a80ceb80-cdf6-11eb-96cd-e7da3a76f81a.png)

From: https://web.dev/manifest-updates/

**Comment by ajhawkings** [comment]
THIS IS ALL GOOGLES FAULT 
WE HATE GOOGLE

**Comment by ajhawkings** [comment]
Google are the standards

**Comment by ajhawkings** [comment]
Wait so we won’t be able to change it next year @HandyHat????

**Comment by HandyHat** [comment]
Next year will be a new url so a new pwa will be needed and people will have to install again. Not sure if currently installed ones will continue to run if we set up a redirect? But once the domain expires that won't work either. Will be a bit of mess icl
