### ISSUE TITLE
Move data from JSON to HTML?

### ISSUE THREAD

**Issue by HandyHat** [YearInfo/Website#7]
@ajhawkings @Epacnoss would like your thoughts?

**Comment by ajhawkings** [comment]
Idm

**Comment by ajhawkings** [comment]
There’s obvs a reason we switched to json (ease of updating??) but idk if the benefits of html outweigh that

**Comment by HandyHat** [comment]
Well basically if we want to add stuff like itemprop and ordered lists etc. it makes more sense to move to html rather than try to edit the parser to handle the edge cases

**Comment by HandyHat** [comment]
Closed in 7f38305
